services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certs:/etc/letsencrypt
      - certbot-htdocs:/var/www/certbot
    environment:
      - DOMAIN=${DOMAIN}

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - certs:/certs
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro

  redisinsight:
    image: redis/redisinsight
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - redisinsight-storage:/db

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - certs:/etc/letsencrypt
      - certbot-htdocs:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --quiet; done'"

volumes:
  certs:
    external: true
  certbot-htdocs:
    external: true
  redisinsight-storage:
    external: false
